[package]
name = "spectra_wallet"
version = "0.1.0"
edition = "2021"

[lib]
name = "spectra_wallet"
crate-type = ["cdylib", "rlib"]

# [features]
# default = []
# python = ["pyo3"]
# pyo3 = ["dep:pyo3"]

[dependencies]
# openssl = { version = "0.10", features = ["vendored"] }

# solana-client = "2.0.5"
# solana-sdk = "2.0.5"

anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
zeroize = "1.8"
image = "0.25"
blake2 = "0.10"
argon2 = "0.5.3"
aes-gcm = "0.10"
ed25519-dalek = "2.0"
secp256k1 = "0.31"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
hex = "0.4"
rand = "0.8"
base58= "0.2"
sha2 = "0.10"
ripemd = "0.1"
pyo3 = { version = "0.21", optional = true }

colored = "3.0.0"
dialoguer = "0.12.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22.1"
